### ISSUE TITLE
Create a Lambda to generate IAM Accounts and Users Registering from the Frontend

### ISSUE THREAD

**Issue by werzl** [werzl/jdmcserver#16]
# Description
We shouldn't rely on one API key for secure access to our Lambdas / Apis. It would be better to have user accounts with IAM roles.

# Tasks
- [ ] Create a 'User' API
- [ ] Create a lambda to generate and store user accounts when someone registers to the website
- [ ] Create admin account to approve user account creation
- [ ] Create a lambda to login and return a JWT so users can login and be authenticated.

**Comment by JoeDurrant** [comment]
Look into cognito, you can create identity pools with admin approval as an option
